/*
 * TopStack (c) Copyright 2012-2013 Transcend Computing, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the License);
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.msi.tough.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RdsAvailabilityZone generated by hbm2java
 */
@Entity
@Table(name = "availability_zone")
public class AvailabilityZoneBean {

    @Id
    @Column(name = "availability_zone")
    private String availabilityZone;

    @Column(name = "bak_window")
    private String preferredBackupWindow;

    @Column(name = "mntn_window")
    private String preferredMaintenanceWindow;

    @Column(name = "cloud_type")
    private String cloudType;

    @Column(name = "def")
    private Boolean default_;

    public String getAvailabilityZone() {
        return availabilityZone;
    }

    public String getCloudType() {
        return cloudType;
    }

    public Boolean getDefault_() {
        return default_;
    }

    public String getPreferredBackupWindow() {
        return preferredBackupWindow;
    }

    public String getPreferredMaintenanceWindow() {
        return preferredMaintenanceWindow;
    }

    public void setAvailabilityZone(String availabilityZone) {
        this.availabilityZone = availabilityZone;
    }

    public void setCloudType(String cloudType) {
        this.cloudType = cloudType;
    }

    public void setDefault_(Boolean default_) {
        this.default_ = default_;
    }

    public void setPreferredBackupWindow(String preferredBackupWindow) {
        this.preferredBackupWindow = preferredBackupWindow;
    }

    public void setPreferredMaintenanceWindow(String preferredMaintenanceWindow) {
        this.preferredMaintenanceWindow = preferredMaintenanceWindow;
    }

}
