/*
 * TopStack (c) Copyright 2012-2013 Transcend Computing, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the License);
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.msi.tough.model.rds;

// Generated May 10, 2011 9:13:49 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RdsDbengine generated by hbm2java
 */

@Entity
@Table(name = "rds_dbengine")
public class RdsDbengine {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long id;

	private String engine;
	private String engine_version;
	private String dbparameterGroupFamily;
	private Boolean _default;
	private String next_minor_version;
	private Date minor_version_release_date;
	private String next_major_version;
	private Date major_version_release_date;

	public String getDbparameterGroupFamily() {
		return dbparameterGroupFamily;
	}

	public Boolean getDefault_() {
		return _default;
	}

	public String getEngine() {
		return engine;
	}

	public String getEngineVersion() {
		return engine_version;
	}

	public long getId() {
		return id;
	}

	public Date getMajorVersionReleaseDate() {
		return major_version_release_date;
	}

	public Date getMinorVersionReleaseDate() {
		return minor_version_release_date;
	}

	public String getNextMajorVersion() {
		return next_major_version;
	}

	public String getNextMinorVersion() {
		return next_minor_version;
	}

	public void setDbparameterGroupFamily(String dbparameterGroupFamily) {
		this.dbparameterGroupFamily = dbparameterGroupFamily;
	}

	public void setDefault_(Boolean _default) {
		this._default = _default;
	}

	public void setEngine(String engine) {
		this.engine = engine;
	}

	public void setEngineVersion(String engineVersion) {
		this.engine_version = engineVersion;
	}

	public void setId(long id) {
		this.id = id;
	}

	public void setMajorVersionReleaseDate(Date majorVersionReleaseDate) {
		this.major_version_release_date = majorVersionReleaseDate;
	}

	public void setMinorVersionReleaseDate(Date minorVersionReleaseDate) {
		this.minor_version_release_date = minorVersionReleaseDate;
	}

	public void setNextMajorVersion(String nextMajorVersion) {
		this.next_major_version = nextMajorVersion;
	}

	public void setNextMinorVersion(String nextMinorVersion) {
		this.next_minor_version = nextMinorVersion;
	}

}
